# Generated by Django 2.2 on 2019-05-15 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_like'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='created',
            new_name='created_at',
        ),
    ]
